/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "metrics"
include(":metrics-server")
include(":core")
include(":agent")
include(":thread-pool-metrics")
include(":jvm-metrics")
include(":metrics-common")
