import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("minxie.space.java-conventions")
    id("com.github.johnrengelman.shadow") version "8.1.1"
    kotlin("jvm") version "1.7.22"
    kotlin("plugin.spring") version "1.7.22"
}

dependencies {
    api("net.bytebuddy:byte-buddy-agent:1.14.3")
    api(project(":jvm-metrics"))
    api(project(":metrics-common"))
    api(project(":metrics-server"))
    api(project(":thread-pool-metrics"))
}

description = "agent"
java.sourceCompatibility = JavaVersion.VERSION_1_8

tasks.withType<KotlinCompile> {
    kotlinOptions {
        freeCompilerArgs = listOf("-Xjsr305=strict")
        jvmTarget = "1.8"
    }
}

tasks.withType<Jar> {
    manifest {
        attributes["Premain-Class"] = "minxie.space.agent.AgentMain"
        attributes["Can-Redefine-Classes"] = "true"
        attributes["Can-Retransform-Classes"] = "true"
        attributes["Boot-Class-Path"] = "lib/core-1.0-SNAPSHOT.jar"
    }
}

tasks.withType<ShadowJar> {
    dependencies {
        relocate("net.bytebuddy", "minxie.space.agent.shade.bytebuddy")
        relocate("org.jetbrains", "minxie.space.agent.shade.jetbrains")
        relocate("io.netty", "minxie.space.agent.shade.netty")
        relocate("org.yaml", "minxie.space.agent.shade.yaml")
    }
}