{
 "title": "JVM-M",
 "description": "Complete dashboard using metrics from prometheus JMX exporter, with drill down per job > instance",
 "tags": [ "JVM" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_info{applicationName = \"$applicationName\"},instance)"
    }
   },
   {
    "name": "mempool",
    "query": {
     "query": "label_values(jvm_memory_pool_bytes_max{applicationName = \"$applicationName\", instance=\"$instance\"}, pool)"
    }
   },
   {
    "name": "memarea",
    "query": {
     "query": "label_values(jvm_memory_bytes_used{applicationName = \"$applicationName\", instance=\"$instance\"}, area)"
    }
   },
   {
    "name": "applicationName",
    "label": "applicationName",
    "query": {
     "query": "label_values(jvm_info{},applicationName)"
    }
   },
   {
    "name": "threadPoolName",
    "query": {
     "query": "label_values(jdk_thread_pool_completed_task_count{applicationName = \"$applicationName\", instance=\"$instance\"}, threadPoolName)"
    }
   },
   {
    "name": "dubboThreadPoolName",
    "query": {
     "query": "label_values(dubbo_thread_pool_completed_task_count{applicationName = \"$applicationName\", instance=\"$instance\"}, threadPoolName)"
    }
   },
   {
    "name": "rocketMQThreadPoolName",
    "query": {
     "query": "label_values(rocketmq_thread_pool_completed_task_count{applicationName = \"$applicationName\", instance=\"$instance\"}, threadPoolName)"
    }
   }
  ]
 },
 "panels": [
  { "title": "总览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_info{applicationName = \"$applicationName\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{applicationName = \"$applicationName\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{applicationName = \"$applicationName\",instance=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_join(jvm_info{applicationName = \"$applicationName\",instance=\"$instance\"}, \"jdk\", \", \", \"vendor\", \"runtime\", \"version\")"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_classes_currently_loaded{applicationName = \"$applicationName\", instance=\"$instance\"}",
     "legendFormat": "loaded"
    }
   ]
  },
  {
   "title": "Available CPUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_AvailableProcessors{applicationName = \"$applicationName\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "System load average",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_SystemLoadAverage{applicationName = \"$applicationName\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_open_fds{applicationName = \"$applicationName\",instance=\"$instance\"}",
     "legendFormat": "process_open_fds"
    },
    {
     "expr": "process_max_fds{applicationName = \"$applicationName\",instance=\"$instance\"}",
     "legendFormat": "process_max_fds"
    }
   ]
  },
  {
   "title": "Class unload",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_classes_unloaded_total{applicationName = \"$applicationName\", instance=\"$instance\"}",
     "legendFormat": "unload"
    }
   ]
  },
  {
   "title": "JDK 线程池完成任务总数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jdk_thread_pool_completed_task_count{applicationName = \"$applicationName\", instance=\"$instance\"})",
     "legendFormat": "Tomcat 完成任务总数"
    }
   ]
  },
  {
   "title": "Dubbo 线程池完成任务总数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dubbo_thread_pool_completed_task_count{applicationName = \"$applicationName\", instance=\"$instance\"})",
     "legendFormat": "Tomcat 完成任务总数"
    }
   ]
  },
  {
   "title": "RocketMQ 线程池完成任务总数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rocketmq_thread_pool_completed_task_count{applicationName = \"$applicationName\", instance=\"$instance\"})",
     "legendFormat": "RocketMQ 完成任务总数"
    }
   ]
  },
  {
   "title": "Tomcat 完成任务总数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tomcat_thread_pool_completed_task_count{applicationName = \"$applicationName\", instance=\"$instance\"}",
     "legendFormat": "Tomcat 完成任务总数"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_CpuLoad{applicationName = \"$applicationName\",instance=\"$instance\"}",
     "legendFormat": "System"
    },
    {
     "expr": "java_lang_OperatingSystem_ProcessCpuLoad{applicationName = \"$applicationName\",instance=\"$instance\"}",
     "legendFormat": "JVM"
    }
   ]
  },
  {
   "title": "Physical memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_TotalPhysicalMemorySize{applicationName = \"$applicationName\",instance=\"$instance\"}",
     "legendFormat": "Total physical memory"
    },
    {
     "expr": "java_lang_OperatingSystem_CommittedVirtualMemorySize{applicationName = \"$applicationName\",instance=\"$instance\"}",
     "legendFormat": "Committed virtual memory"
    },
    {
     "expr": "java_lang_OperatingSystem_FreeMemorySize{applicationName = \"$applicationName\",instance=\"$instance\"}",
     "legendFormat": "Free physical memory"
    }
   ]
  },
  {
   "title": "垃圾回收",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC count increase",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(jvm_gc_collection_seconds_count{applicationName = \"$applicationName\",instance=~\"$instance\"}[$__interval])",
       "legendFormat": "{{gc}}"
      }
     ]
    },
    {
     "title": "GC time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "increase(jvm_gc_collection_seconds_sum{applicationName = \"$applicationName\",instance=~\"$instance\"}[$__interval])",
       "legendFormat": "{{gc}}"
      }
     ]
    }
   ]
  },
  {
   "title": "线程状态",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threads used",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_current{applicationName = \"$applicationName\",instance=\"$instance\"}",
       "legendFormat": "JVM current threads"
      },
      {
       "expr": "jvm_threads_daemon{applicationName = \"$applicationName\",instance=\"$instance\"}",
       "legendFormat": "JVM daemon threads"
      },
      {
       "expr": "jvm_threads_deadlocked{applicationName = \"$applicationName\",instance=\"$instance\"}",
       "legendFormat": "JVM deadlocked threads"
      }
     ]
    },
    {
     "title": "Thread State",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_state{applicationName = \"$applicationName\",instance=\"$instance\"}",
       "legendFormat": "{{state}}"
      },
      {
       "expr": "jvm_threads_deadlocked{applicationName = \"$applicationName\",instance=\"$instance\"}",
       "legendFormat": "DEAD_LOCKED"
      },
      {
       "expr": "jvm_threads_current{applicationName = \"$applicationName\",instance=\"$instance\"}",
       "legendFormat": "LIVE_THREAD"
      }
     ]
    },
    {
     "title": "Thread Info",
     "type": "status-history",
     "gridPos": { "h": 24, "w": 24, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "jvm_threads{applicationName = \"$applicationName\",instance=\"$instance\"}",
       "legendFormat": "{{threadName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "堆内存",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory area [$memarea]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "repeat": "memarea",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{area=\"$memarea\",applicationName = \"$applicationName\",instance=\"$instance\"}",
       "legendFormat": "Used"
      },
      {
       "expr": " jvm_memory_bytes_max{area=\"$memarea\",applicationName = \"$applicationName\",instance=\"$instance\"}",
       "legendFormat": "Max"
      },
      {
       "expr": "jvm_memory_bytes_used{area=\"$memarea\",applicationName = \"$applicationName\",instance=\"$instance\"} / jvm_memory_bytes_max >= 0",
       "legendFormat": "Usage %"
      }
     ]
    },
    {
     "title": "Memory pool [$mempool]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "repeat": "mempool",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_max{pool=\"$mempool\",applicationName = \"$applicationName\",instance=\"$instance\"}",
       "legendFormat": "Max"
      },
      {
       "expr": "jvm_memory_pool_bytes_used{pool=\"$mempool\",applicationName = \"$applicationName\",instance=\"$instance\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_pool_bytes_committed{pool=\"$mempool\",applicationName = \"$applicationName\",instance=\"$instance\"}",
       "legendFormat": "Committed"
      }
     ]
    }
   ]
  },
  {
   "title": "JDK 线程池",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "JDK线程池[$threadPoolName] 完成任务数",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
     "repeat": "threadPoolName",
     "targets": [
      {
       "expr": "increase(jdk_thread_pool_completed_task_count{threadPoolName=\"$threadPoolName\",applicationName = \"$applicationName\", instance=\"$instance\"}[$__interval])",
       "legendFormat": "${threadPoolName} 完成任务数"
      }
     ]
    },
    {
     "title": "JDK Thread Pool[$threadPoolName]",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 252 },
     "repeat": "threadPoolName",
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "jdk_thread_pool_active_count{threadPoolName=\"$threadPoolName\",applicationName = \"$applicationName\",instance=\"$instance\"}",
       "legendFormat": "active_count"
      },
      {
       "expr": "jdk_thread_pool_core_pool_size{threadPoolName=\"$threadPoolName\",applicationName = \"$applicationName\",instance=\"$instance\"}",
       "legendFormat": "core_pool_size"
      },
      {
       "expr": "jdk_thread_pool_maximum_pool_size{threadPoolName=\"$threadPoolName\",applicationName = \"$applicationName\",instance=\"$instance\"}",
       "legendFormat": "maximum_pool_size"
      },
      {
       "expr": "jdk_thread_pool_queue_size{threadPoolName=\"$threadPoolName\",applicationName = \"$applicationName\",instance=\"$instance\"}",
       "legendFormat": "queue_size"
      }
     ]
    }
   ]
  },
  {
   "title": "Dubbo线程池",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dubbo线程池[$dubboThreadPoolName] 完成任务数",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 6 },
     "repeat": "dubboThreadPoolName",
     "targets": [
      {
       "expr": "increase(dubbo_thread_pool_completed_task_count{threadPoolName=\"$dubboThreadPoolName\",applicationName = \"$applicationName\", instance=\"$instance\"}[$__interval])",
       "legendFormat": "${dubboThreadPoolName} 完成任务数"
      }
     ]
    },
    {
     "title": "Dubbo Thread Pool[$dubboThreadPoolName]",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 18 },
     "repeat": "dubboThreadPoolName",
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "dubbo_thread_pool_active_count{threadPoolName=\"$dubboThreadPoolName\",applicationName = \"$applicationName\",instance=\"$instance\"}",
       "legendFormat": "active_count"
      },
      {
       "expr": "dubbo_thread_pool_core_pool_size{threadPoolName=\"$dubboThreadPoolName\",applicationName = \"$applicationName\",instance=\"$instance\"}",
       "legendFormat": "core_pool_size"
      },
      {
       "expr": "dubbo_thread_pool_maximum_pool_size{threadPoolName=\"$dubboThreadPoolName\",applicationName = \"$applicationName\",instance=\"$instance\"}",
       "legendFormat": "maximum_pool_size"
      },
      {
       "expr": "dubbo_thread_pool_queue_size{threadPoolName=\"$dubboThreadPoolName\",applicationName = \"$applicationName\",instance=\"$instance\"}",
       "legendFormat": "queue_size"
      }
     ]
    }
   ]
  },
  {
   "title": "Tomcat 线程池",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tomcat 完成任务数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "increase(tomcat_thread_pool_completed_task_count{applicationName = \"$applicationName\", instance=\"$instance\"}[$__interval])",
       "legendFormat": "Tomcat 完成任务数"
      }
     ]
    },
    {
     "title": "Tomcat Thread Pool",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "tomcat_thread_pool_active_count{applicationName = \"$applicationName\",instance=\"$instance\"}",
       "legendFormat": "active_count"
      },
      {
       "expr": "tomcat_thread_pool_core_pool_size{applicationName = \"$applicationName\",instance=\"$instance\"}",
       "legendFormat": "core_pool_size"
      },
      {
       "expr": "tomcat_thread_pool_maximum_pool_size{applicationName = \"$applicationName\",instance=\"$instance\"}",
       "legendFormat": "maximum_pool_size"
      },
      {
       "expr": "tomcat_thread_pool_queue_size{applicationName = \"$applicationName\",instance=\"$instance\"}",
       "legendFormat": "queue_size"
      }
     ]
    }
   ]
  },
  { "title": "RocketMQ 线程池", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "RocketMQ Thread Pool[$rocketMQThreadPoolName]",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 43 },
   "repeat": "rocketMQThreadPoolName",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rocketmq_thread_pool_active_count{threadPoolName=\"$rocketMQThreadPoolName\",applicationName = \"$applicationName\",instance=\"$instance\"}",
     "legendFormat": "active_count"
    },
    {
     "expr": "rocketmq_thread_pool_core_pool_size{threadPoolName=\"$rocketMQThreadPoolName\",applicationName = \"$applicationName\",instance=\"$instance\"}",
     "legendFormat": "core_pool_size"
    },
    {
     "expr": "rocketmq_thread_pool_maximum_pool_size{threadPoolName=\"$rocketMQThreadPoolName\",applicationName = \"$applicationName\",instance=\"$instance\"}",
     "legendFormat": "maximum_pool_size"
    },
    {
     "expr": "rocketmq_thread_pool_queue_size{threadPoolName=\"$rocketMQThreadPoolName\",applicationName = \"$applicationName\",instance=\"$instance\"}",
     "legendFormat": "queue_size"
    }
   ]
  },
  {
   "title": "RocketMQ线程池[$rocketMQThreadPoolName] 完成任务数",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 55 },
   "repeat": "rocketMQThreadPoolName",
   "targets": [
    {
     "expr": "increase(rocketmq_thread_pool_completed_task_count{threadPoolName=\"$rocketMQThreadPoolName\",applicationName = \"$applicationName\", instance=\"$instance\"}[$__interval])",
     "legendFormat": "${rocketMQThreadPoolName} 完成任务数"
    }
   ]
  }
 ]
}